matrix:
  include:
    - language: python
    - language: ruby
      before_install:
        - gem install bundler
branches:
  only:
    - sources
before_script:
  - chmod +x ./cibuild

script: ./cibuild
exclude: [vendor]
sudo: false