matrix:
  include:
    - language: python
    - language: ruby
      rvm:
        - 2.6
branches:
  only:
    - sources
before_script:
  - chmod +x ./cibuild

script: ./cibuild
exclude: [vendor]
sudo: false