stages:
  - python-setup
  - ruby-setup
  - push-github
matrix:
  include:
    - language: python
      stage: "python-setup"
      before_script:
        - pip install pyyaml
      script:
        - python scripts/generate_jekyll_blueprint.py
        - python scripts/prepare_gitignore_for_deployment.py
    - language: ruby
      stage: "ruby-setup"
      script:
        - jekyll build
      rvm:
        - 2.6
    - language: minimal
      stage: "push-github"
      before_script:
        - chmod +x ./cibuild
      script: ./cibuild
branches:
  only:
    - sources
exclude: [vendor]
sudo: false