language: ruby
rvm:
  - 2.6
before_script:
  - chmod +x ./scripts/github-clone
  - chmod +x ./scripts/github-push
script:
  - ./scripts/github-clone
  - python scripts/generate_jekyll_blueprint.py
  - python scripts/prepare_gitignore_for_deployment.py
  - jekyll build
  - ./scripts/github-push
branches:
  only:
    - sources
exclude: [vendor]
sudo: false