plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 20

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "authors/*"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"