plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 20
  sort_reverse: 'true'

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "authors/*"
    values:
      layout: "author"
  - scope:
      path: "titles/*"
    values:
      layout: "title"
  - scope:
      path: ""
    values:
      layout: "default"