#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# push
cd _site
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git remote rm origin
git remote add origin https://${GH_TOKEN}@github.com/VictorAlbertos/VictorAlbertos.github.io.git 
git push --force origin master